version: '3'

services:
  gameDB_postgresql:
    image: postgres:12
    container_name: game_database
    volumes:
      - game_database:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - gameDB_network

  userDB_postgresql:
    image: postgres:12
    container_name: user_database
    volumes:
      - user_database:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5431:5432"
    networks:
      - userDB_network
  api:
    build: .
    command: python gameAPI/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    restart: always
    ports:
      - "8000:8000"
    networks:
      - gameDB_network
      - userDB_network
    depends_on:
      - gameDB_postgresql
      - userDB_postgresql
    


volumes:
  game_database:
    external: true
  user_database:
    external: true
    
networks:
  gameDB_network:
    external: true
  userDB_network:
    external: true
