version: '3'

services:
  gameDB_postgresql:
    image: postgres:14
    container_name: game_database
    volumes:
      - game_database:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - gameDB_network

  userDB_postgresql:
    image: postgres:14
    container_name: user_database
    volumes:
      - user_database:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5431:5431"
    networks:
      - userDB_network


volumes:
  game_database:
    external: true
  user_database:
    external: true
    
networks:
  gameDB_network:
    external: true
  userDB_network:
    external: true